server:
  port: 8080

spring:
  application:
    name: sentinel-feign-provider  # 设置应用的名称
  cloud:
    nacos:
      discovery:
        # ip: localhost
        server-addr: localhost:8848  # 注意 ip 和 server-addr的区别


