server:
  port: 8888

spring:
  application:
    name: sentinel-gateway  # 设置应用的名称
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9000  # 设置sentinel链接控制台的主机地址和端口
    nacos:
      discovery:
        # ip: localhost
        server-addr: localhost:8848  # 注意 ip 和 server-addr的区别
    gateway:
      discovery:
        locator:
          enabled: true # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能
          lower-case-service-id: true # service区分大小写
      routes:
        - id: sentinel-feign-consumer
          uri: lb://sentinel-feign-consumer
          predicates:
            - Path=/consumer/**,/lvchao/**